#!/bin/sh

# Run prettier directly with a more limited scope to prevent errors
npx prettier --write "frontend/**/*.{js,jsx,ts,tsx}" "backend/src/**/*.{js,ts}" "*.{js,json,md}"

# Echo a message to confirm hook ran successfully
echo "Pre-commit hook ran successfully"